source/accounts/urls.py
from django.urls import path
from .views import UserCreateView, UserLoginView, UserLogoutView, UserProfileView, EditProfileView, UserDetailView
from django.contrib.auth.views import LogoutView
app_name = 'accounts'

urlpatterns = [
    path('register/', UserCreateView.as_view(), name='user_create'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('profile/edit/', EditProfileView.as_view(), name='edit_profile'),
    path('user/<int:pk>/', UserDetailView.as_view(), name='user_detail'),
]

source/hello/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('webapp.urls')),
]

source/accounts/models.py
from django.contrib.auth.models import User
from django.db import models

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=15)

    # Другие поля профиля

    def __str__(self):
        return self.user.username

source/accounts/forms.py
from django import forms
from .models import UserProfile
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['phone']


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

source/accounts/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import TemplateView, CreateView, DetailView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .forms import CustomUserCreationForm, UserProfileForm
from .models import UserProfile
from django.contrib.auth.models import User


class UserCreateView(CreateView):
    template_name = 'user_create.html'
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('webapp:announcement_list')


class UserLoginView(LoginView):
    template_name = 'login.html'


class UserLogoutView(LogoutView):
    next_page = reverse_lazy('webapp:announcement_list')


class UserProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_phone'] = self.request.user.profile.phone
        context['user_announcements'] = self.request.user.announcement_set.exclude(status='Удалено')
        return context


class EditProfileView(LoginRequiredMixin, UpdateView):
    model = UserProfile
    form_class = UserProfileForm
    template_name = 'edit_profile.html'
    success_url = reverse_lazy('accounts:profile')

    def get_object(self, queryset=None):
        return self.request.user.profile


class UserDetailView(DetailView):
    model = User  # Assuming you want to display details for a User model
    template_name = 'user_detail.html'  # Replace with the actual template file name
    context_object_name = 'user'  # The variable name in the template

source/accounts/templates/edit_profile.html
{% extends 'base.html' %}

{% block title %}Edit Profile{% endblock %}

{% block content %}
    <h2>Edit Profile</h2>
    <form method="post" class="form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save Changes</button>
    </form>
{% endblock %}

source/accounts/templates/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
    <h2>Login</h2>
    <form method="post" class="form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
{% endblock %}

source/accounts/templates/profile.html
{% extends 'base.html' %}

{% block title %}Profile{% endblock %}

{% block content %}
    <h2>Welcome, {{ request.user.username }}!</h2>
    <p>Phone: {{ user_phone }}</p>
    <h3>Your Announcements:</h3>
    {% for announcement in user_announcements %}
        <p>{{ announcement.heading }} - {{ announcement.price }}</p>
    {% endfor %}
{% endblock %}

source/accounts/templates/user_create.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}

{% block content %}
  <h2>Register</h2>
  <form method="post" action="{% url 'accounts:user_create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
  </form>
{% endblock %}

source/accounts/templates/user_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ user.username }} - User Profile
{% endblock %}

{% block content %}
    <div class="container mt-5">
        <h2>{{ user.username }}'s Profile</h2>
        <p>Phone: {{ user.phone }}</p>
        {% if user == request.user %}
            <p><a href="{% url 'accounts:edit_profile' %}">Edit Profile</a></p>
        {% endif %}
    </div>
{% endblock %}